-- Run this once if the existing Supabase project shows:
-- Could not find the table 'public.patch_orders' in the schema cache

create table if not exists public.patch_orders (
  id text primary key default ('PM-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  customer_name text not null,
  customer_phone text not null default '',
  shipping_address text not null default '',
  total_price integer not null default 0,
  note text not null default '',
  status text not null default 'new' check (status in ('new','confirmed','completed','closed')),
  created_at timestamptz not null default now()
);
create table if not exists public.patch_order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.patch_orders(id) on delete cascade,
  patch_id text not null references public.patches(id) on delete restrict,
  patch_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null default 0,
  line_total integer not null default 0
);
create index if not exists patch_orders_created_at_idx on public.patch_orders(created_at desc);
alter table public.patch_orders enable row level security;
alter table public.patch_order_items enable row level security;
grant all on table public.patch_orders to service_role;
grant all on table public.patch_order_items to service_role;
grant usage, select on sequence public.patch_order_items_id_seq to service_role;
notify pgrst, 'reload schema';
