'use client';

import { useEffect, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';

const PRODUCT_VIEWS=[
  ['front','Mặt trước'],
  ['left_sleeve','Tay áo trái'],
  ['right_sleeve','Tay áo phải'],
  ['back','Lưng áo']
];
const PRODUCT_VIEW_SETS={shirt:PRODUCT_VIEWS,bag:[['front','Mặt trước'],['back','Mặt sau']]};
const productTypeLabel=t=>t==='bag'?'Túi':'Áo';

export default function Admin(){
 const [user,setUser]=useState(null),[email,setEmail]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState('requests'),[items,setItems]=useState([]),[summary,setSummary]=useState({}),[settings,setSettings]=useState({}),[products,setProducts]=useState([]),[patches,setPatches]=useState([]),[editingProduct,setEditingProduct]=useState(null),[editingPatch,setEditingPatch]=useState(null),[productType,setProductType]=useState('shirt'),[msg,setMsg]=useState('');
 const supa=()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
 const call=async(path,opts={})=>{const r=await fetch('/api/admin/'+path,opts),d=await r.json();if(!r.ok)throw Error(d.error||'Có lỗi xảy ra');return d;};
 async function refresh(){setLoading(true);try{const {data:{user:u}}=await supa().auth.getUser();setUser(u);if(u){const [s,d,p,a,z]=await Promise.all([call('summary'),call('designs'),call('products'),call('patches'),call('settings')]);setSummary(s);setItems(d.items);setProducts(p.items);setPatches(a.items);setSettings(z.settings);}}catch(e){setMsg(e.message);}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 async function login(e){e.preventDefault();setMsg('Đang gửi link đăng nhập…');const {error}=await supa().auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/auth/callback`}});setMsg(error?.message||'Đã gửi link đăng nhập vào email.');}
 async function status(id,status){await call('designs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});await refresh();}
 async function remove(section,id){if(!confirm('Xóa mục này?'))return;await fetch(`/api/admin/${section}?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(section==='patches'&&editingPatch?.id===id)setEditingPatch(null);if(section==='products'&&editingProduct?.id===id){setEditingProduct(null);setProductType('shirt');}await refresh();}
 function editProduct(p){setEditingProduct(p);setProductType(p.product_type||'shirt');setMsg('Đang sửa sản phẩm base: '+p.name);setTimeout(()=>document.querySelector('.product-edit-card')?.scrollIntoView({behavior:'smooth',block:'start'}),50);}
 function editPatch(p){setEditingPatch(p);setMsg('Đang sửa patch: '+p.name);setTimeout(()=>document.querySelector('.patch-edit-card')?.scrollIntoView({behavior:'smooth',block:'start'}),50);}
 async function saveSettings(e){e.preventDefault();try{const b={...settings,sizes:String(settings.sizes||'S,M,L,XL').split(',').map(x=>x.trim()).filter(Boolean),retentionDays:Number(settings.retentionDays)||30,adminEmails:String(settings.adminEmails||'').split(',').map(x=>x.trim()).filter(Boolean)};await call('settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});setMsg('Đã lưu cài đặt.');}catch(e){setMsg(e.message);}}
 async function upload(file){const f=new FormData();f.set('file',file);const d=await call('upload',{method:'POST',body:f});return d.image_url;}
 async function saveProduct(e){
  e.preventDefault();
  const form=e.currentTarget,f=new FormData(form),view_images={};
  const product_type=String(f.get('product_type')||'shirt');
  for(const [key] of PRODUCT_VIEW_SETS[product_type]||PRODUCT_VIEW_SETS.shirt){
    const file=f.get(`${key}_file`),url=String(f.get(`${key}_url`)||'').trim();
    if(file?.size)view_images[key]=await upload(file);
    else if(url)view_images[key]=url;
  }
  const image_url=view_images.front||'/assets/blank-tee.webp';
  const b={id:f.get('id')||undefined,sku:String(f.get('sku')||'').trim()||undefined,product_type,name:f.get('name'),color:f.get('color'),hex:f.get('hex'),image_url,view_images,sizes:String(f.get('sizes')).split(',').map(x=>x.trim()).filter(Boolean),price:f.get('price')?Number(f.get('price')):null,active:true};
  await call('products',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});
  setEditingProduct(null);setProductType('shirt');form.reset();await refresh();setMsg(f.get('id')?'Đã cập nhật sản phẩm base / SKU.':'Đã lưu sản phẩm base / SKU.');
 }
 async function savePatch(e){e.preventDefault();const f=new FormData(e.currentTarget);let image_url=String(f.get('image_url')||'').trim();if(f.get('file')?.size)image_url=await upload(f.get('file'));const b={id:f.get('id')||undefined,name:f.get('name'),image_url,width_cm:Number(f.get('width_cm'))||4,height_cm:Number(f.get('height_cm'))||4,price:f.get('price')?Number(f.get('price')):null,quote:String(f.get('quote')||'').trim(),active:true,sort_order:Number(f.get('sort_order'))||100};await call('patches',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});setEditingPatch(null);e.currentTarget.reset();await refresh();setMsg(f.get('id')?'Đã cập nhật patch.':'Đã lưu patch.');}
 const money=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?`${new Intl.NumberFormat('vi-VN').format(Number(v))}đ`:'Chưa set';
 const patchText=d=>(d.patches||[]).map(x=>`${x.name}${x.view?` · ${viewLabel(x.view)}`:''} · ${money(x.price)}`).join(', ');
 const viewLabel=id=>PRODUCT_VIEWS.find(([key])=>key===id)?.[1]||'Mặt trước';

 if(loading)return <main className="admin-shell"><div className="admin-loading">Đang tải dashboard…</div></main>;
 if(!user)return <main className="admin-shell"><div className="login-card"><a className="brand" href="/"><span className="brand-mark">P</span> Patchie</a><div className="eyebrow">KHU VỰC QUẢN TRỊ</div><h1>Đăng nhập shop</h1><p>Đăng nhập bằng email được thêm vào biến <code>ADMIN_EMAILS</code>.</p><form onSubmit={login}><label>Email quản trị<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@patchie.vn"/></label><button className="button dark full">Gửi link đăng nhập</button></form>{msg&&<p className="admin-msg">{msg}</p>}<a className="back-link" href="/">← Về studio</a></div></main>;
 return <main className="admin-shell"><header className="admin-top"><a className="brand" href="/"><span className="brand-mark">P</span> Patchie <small>ADMIN</small></a><div>{user.email}<button className="admin-logout" onClick={async()=>{await supa().auth.signOut();setUser(null);}}>Đăng xuất</button></div></header><div className="admin-layout"><nav className="admin-nav">{[['requests','Yêu cầu thiết kế'],['products','Sản phẩm base'],['patches','Thư viện patch'],['settings','Cài đặt']].map(([id,label])=><button key={id} className={tab===id?'sel':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><section className="admin-content"><div className="admin-heading"><div><small>PATCHIE STUDIO</small><h1>{({requests:'Yêu cầu thiết kế',products:'Sản phẩm base',patches:'Thư viện patch',settings:'Cài đặt shop'})[tab]}</h1></div><a href="/">Mở studio ↗</a></div>{msg&&<div className="admin-msg">{msg}</div>}
 {tab==='requests'&&<><div className="stats-grid">{[['Yêu cầu mới',summary.new||0],['Đang xem',summary.review||0],['Đã xác nhận',summary.confirmed||0],['Sản phẩm',summary.catalog||0]].map(([l,n])=><div className="stat" key={l}><b>{n}</b><span>{l}</span></div>)}</div><div className="admin-card"><h2>Danh sách yêu cầu</h2><div className="table-scroll"><table><thead><tr><th>Mã / khách</th><th>Liên hệ / nhận hàng</th><th>Base & size</th><th>Patch</th><th>Tổng đơn</th><th>Mockup</th><th>Trạng thái</th><th></th></tr></thead><tbody>{items.map(d=><tr key={d.id}><td><b>{d.id}</b><br/>{d.customer_name}<small>{new Date(d.created_at).toLocaleDateString('vi-VN')}</small></td><td>{d.customer_phone||'Chưa có SĐT'}<small>{d.shipping_address||'Chưa có địa chỉ'}</small></td><td>{d.products?.name||d.product_id}<br/>Size {d.size} · {d.mode==='shop'?'Shop ủi':'Tự ủi'}<small>Base: {money(d.product_price ?? d.products?.price)}</small></td><td>{patchText(d)}</td><td><b>{money(d.total_price)}</b></td><td>{d.imageUrl&&<a href={d.imageUrl} target="_blank">Xem ảnh ↗</a>}</td><td><select value={d.status} onChange={e=>status(d.id,e.target.value)}>{['new','review','confirmed','completed','closed'].map(s=><option key={s}>{s}</option>)}</select></td><td><button className="delete-btn" onClick={()=>remove('designs',d.id)}>Xóa</button></td></tr>)}</tbody></table>{!items.length&&<p>Chưa có yêu cầu thiết kế.</p>}</div></div></>}
 {tab==='products'&&<><div className="admin-card product-edit-card"><h2>{editingProduct?'Sửa sản phẩm base / SKU':'Thêm sản phẩm base / SKU'}</h2><form key={editingProduct?.id||'new-product'} className="edit-form product-form" onSubmit={saveProduct}><input type="hidden" name="id" defaultValue={editingProduct?.id||''}/><input name="sku" defaultValue={editingProduct?.sku||''} placeholder="SKU, ví dụ TEE-OVS-OFW hoặc BAG-CANVAS"/><select name="product_type" value={productType} onChange={e=>setProductType(e.target.value)}><option value="shirt">Áo</option><option value="bag">Túi</option></select><input name="name" required defaultValue={editingProduct?.name||''} placeholder="Tên sản phẩm base"/><input name="color" required defaultValue={editingProduct?.color||''} placeholder="Tên màu"/><input name="hex" defaultValue={editingProduct?.hex||'#f5f1e8'} placeholder="#hex"/><input name="sizes" defaultValue={(editingProduct?.sizes||['S','M','L','XL']).join(', ')} placeholder="Sizes, cách nhau bằng dấu phẩy"/><input name="price" type="number" defaultValue={editingProduct?.price??''} placeholder="Giá sản phẩm base"/><div className="view-upload-grid">{(PRODUCT_VIEW_SETS[productType]||PRODUCT_VIEW_SETS.shirt).map(([key,label])=><fieldset key={key}><legend>{label}</legend><input name={`${key}_file`} type="file" accept="image/png,image/jpeg,image/webp"/><input name={`${key}_url`} defaultValue={editingProduct?.view_images?.[key]||(key==='front'?(editingProduct?.image_url||(!editingProduct?'/assets/blank-tee.webp':'')):'')} placeholder={`URL ảnh ${label.toLowerCase()}`}/></fieldset>)}</div><button className="button dark">{editingProduct?'Lưu thay đổi':'Thêm sản phẩm'}</button>{editingProduct&&<button type="button" className="button ghost" onClick={()=>{setEditingProduct(null);setProductType('shirt');}}>Hủy sửa</button>}</form></div><div className="admin-card"><h2>Đang có</h2>{products.map(p=><div className="catalog-row" key={p.id}><img src={(p.view_images?.front)||p.image_url}/><b>{p.name}</b><span>{productTypeLabel(p.product_type)} · {p.color} · {(p.sizes||[]).join(', ')}{p.sku?` · SKU ${p.sku}`:''} · {money(p.price)}<small>{Object.values(p.view_images||{}).filter(Boolean).length}/{(PRODUCT_VIEW_SETS[p.product_type||'shirt']||PRODUCT_VIEW_SETS.shirt).length} ảnh mockup</small></span><div className="admin-actions"><button className="edit-btn" onClick={()=>editProduct(p)}>Sửa</button><button className="delete-btn" onClick={()=>remove('products',p.id)}>Xóa</button></div></div>)}</div></>}
 {tab==='patches'&&<><div className="admin-card patch-edit-card"><h2>{editingPatch?'Sửa patch':'Thêm patch'}</h2><form key={editingPatch?.id||'new-patch'} className="edit-form" onSubmit={savePatch}><input type="hidden" name="id" defaultValue={editingPatch?.id||''}/><input name="name" required defaultValue={editingPatch?.name||''} placeholder="Tên patch"/><input name="width_cm" type="number" step="0.1" defaultValue={editingPatch?.width_cm||4} placeholder="Rộng (cm)"/><input name="height_cm" type="number" step="0.1" defaultValue={editingPatch?.height_cm||4} placeholder="Cao (cm)"/><input name="price" type="number" defaultValue={editingPatch?.price??''} placeholder="Giá (để trống nếu chưa chốt)"/><input name="file" type="file" accept="image/png,image/jpeg,image/webp"/><input name="image_url" defaultValue={editingPatch?.image_url||''} placeholder="Hoặc URL ảnh có sẵn"/><input name="quote" defaultValue={editingPatch?.quote||''} placeholder="Quote khi khách chọn patch"/><input name="sort_order" type="number" defaultValue={editingPatch?.sort_order||100} placeholder="Thứ tự hiển thị"/><button className="button dark">{editingPatch?'Lưu thay đổi':'Thêm patch'}</button>{editingPatch&&<button type="button" className="button ghost" onClick={()=>setEditingPatch(null)}>Hủy sửa</button>}</form></div><div className="patch-admin-grid">{patches.map(p=><div className="admin-patch" key={p.id}><img src={p.image_url}/><b>{p.name}</b><small>{p.width_cm} × {p.height_cm} cm · {money(p.price)}{p.quote?" · "+p.quote:""}</small><div className="admin-actions"><button className="edit-btn" onClick={()=>editPatch(p)}>Sửa</button><button className="delete-btn" onClick={()=>remove('patches',p.id)}>Xóa</button></div></div>)}</div></>}
 {tab==='settings'&&<div className="admin-card"><h2>Thông tin website</h2><form className="settings-form" onSubmit={saveSettings}><label>Link Messenger<input value={settings.messengerUrl||''} onChange={e=>setSettings({...settings,messengerUrl:e.target.value})} placeholder="https://m.me/ten-shop"/></label><label>Size áo mặc định<input value={Array.isArray(settings.sizes)?settings.sizes.join(', '):settings.sizes||''} onChange={e=>setSettings({...settings,sizes:e.target.value})} placeholder="S, M, L, XL"/></label><label>Thời hạn lưu yêu cầu (ngày)<input type="number" min="1" max="3650" value={settings.retentionDays||30} onChange={e=>setSettings({...settings,retentionDays:e.target.value})}/></label><label>Email admin bổ sung, ngăn cách bằng dấu phẩy<input value={Array.isArray(settings.adminEmails)?settings.adminEmails.join(', '):settings.adminEmails||''} onChange={e=>setSettings({...settings,adminEmails:e.target.value})}/></label><label className="wide">Thông báo quyền riêng tư<textarea rows="4" value={settings.privacyText||''} onChange={e=>setSettings({...settings,privacyText:e.target.value})}/></label><button className="button dark">Lưu cài đặt</button></form><p className="admin-help">Email admin chính được quản lý trong biến môi trường ADMIN_EMAILS trên Vercel. Danh sách bổ sung có thể cập nhật tại đây.</p></div>}
 </section></div></main>;
}
