'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

const STARTER=[
  {id:'patch-pink',name:'Mũ xanh lá',image_url:'/assets/patch-pink-cap.webp',width_cm:1,height_cm:1},
  {id:'patch-black',name:'Mặt nạ xanh',image_url:'/assets/patch-black-green.webp',width_cm:1,height_cm:1},
  {id:'patch-red',name:'Mũ vàng',image_url:'/assets/patch-red-white.webp',width_cm:1,height_cm:1},
  {id:'patch-yellow',name:'Mũ xanh dương',image_url:'/assets/patch-yellow-blue.webp',width_cm:1,height_cm:1}
];

export default function Home(){
  const [catalog,setCatalog]=useState({products:[{id:'base-offwhite',name:'Áo thun oversized',color:'Off-white',hex:'#f5f1e8',image_url:'/assets/blank-tee.webp',sizes:['S','M','L','XL']}],patches:STARTER,settings:{sizes:['S','M','L','XL'],messengerUrl:'',privacyText:'Shop dùng thông tin này để xử lý yêu cầu thiết kế.'}});
  const [chosen,setChosen]=useState(STARTER[0].id),[placed,setPlaced]=useState([]),[mode,setMode]=useState('diy'),[productId,setProductId]=useState('base-offwhite'),[size,setSize]=useState(''),[name,setName]=useState(''),[note,setNote]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[order,setOrder]=useState(null);
  const stage=useRef(null),drag=useRef(null);
  const product=catalog.products.find(x=>x.id===productId)||catalog.products[0];
  const sizes=product?.sizes?.length?product.sizes:catalog.settings.sizes||[];
  const chosenPatch=catalog.patches.find(x=>x.id===chosen);
  const show=(s)=>{setToast(s);setTimeout(()=>setToast(''),2600)};
  useEffect(()=>{fetch('/api/catalog').then(r=>r.json()).then(d=>{if(d.products?.length&&d.patches?.length){setCatalog(d);setProductId(d.products[0].id);setChosen(d.patches[0].id);}}).catch(()=>{});},[]);
  function add(){if(placed.length>=6)return show('Bố cục tối đa 6 patch.');setPlaced(a=>[...a,{uid:crypto.randomUUID(),patchId:chosen,x:.52+Math.random()*.08,y:.39+Math.random()*.1}]);}
  function move(e){if(!drag.current||!stage.current)return;const r=stage.current.getBoundingClientRect();setPlaced(a=>a.map(x=>x.uid===drag.current?{...x,x:Math.max(.18,Math.min(.82,(e.clientX-r.left)/r.width)),y:Math.max(.16,Math.min(.84,(e.clientY-r.top)/r.height))}:x));}
  async function makePNG(){const c=document.createElement('canvas');c.width=1200;c.height=1200;const ctx=c.getContext('2d');const draw=src=>new Promise((res,rej)=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>res(im);im.onerror=rej;im.src=src;});const tee=await draw(product?.image_url||'/assets/blank-tee.webp');ctx.fillStyle='#f8f6ef';ctx.fillRect(0,0,1200,1200);ctx.drawImage(tee,0,0,1200,1200);for(const item of placed){const p=catalog.patches.find(x=>x.id===item.patchId);if(!p)continue;const im=await draw(p.image_url);const w=18,h=18;ctx.drawImage(im,item.x*1200-w/2,item.y*1200-h/2,w,h);}return await new Promise(resolve=>c.toBlob(resolve,'image/png'));}
  async function save(){if(!placed.length)throw Error('Thêm ít nhất một patch trước nhé.');if(!name.trim())throw Error('Nhập tên để shop nhận diện yêu cầu.');if(!size)throw Error('Chọn size áo trước nhé.');if(!consent)throw Error('Xác nhận quyền riêng tư để tiếp tục.');const blob=await makePNG();const f=new FormData();f.set('name',name.trim());f.set('size',size);f.set('mode',mode);f.set('productId',productId);f.set('note',note);f.set('patches',JSON.stringify(placed.map(x=>({patchId:x.patchId,x:x.x,y:x.y}))));f.set('mockup',blob,'patchie-mockup.png');f.set('consent','true');const r=await fetch('/api/designs',{method:'POST',body:f});const d=await r.json();if(!r.ok)throw Error(d.error||'Chưa lưu được thiết kế.');return {id:d.id,blob};}
  function orderMessage(id){return `Chào Patchie! Mình muốn đặt áo theo mã đơn ${id}.\nMã đơn: ${id}\nCách hoàn thiện: ${mode==='shop'?'Shop ủi giúp':'Tự ủi tại nhà'}\nÁo: ${product?.name||'Áo base'}\nSize: ${size}\nPatch: ${placed.map(x=>catalog.patches.find(p=>p.id===x.patchId)?.name).filter(Boolean).join(', ')}\nGhi chú: ${note||'Không có'}`;}
  async function copyOrder(){if(!order?.id)return;try{await navigator.clipboard.writeText(order.id);show('Đã copy mã đơn. Dán vào Messenger để shop đi đơn nhé.');}catch{show('Không copy tự động được. Bạn có thể copy mã đơn thủ công.');}}
  async function openMessenger(){if(!order)return;if(catalog.settings.messengerUrl){try{await navigator.clipboard.writeText(order.text);}catch{}window.open(catalog.settings.messengerUrl,'_blank','noopener,noreferrer');}else show('Shop chưa cài link Messenger trong admin.');}
  async function send(){setBusy(true);try{const {id}=await save();const text=orderMessage(id);setOrder({id,text});try{await navigator.clipboard.writeText(text);}catch{}show(`Đã tạo mã đơn ${id}. Copy mã rồi gửi shop qua Messenger nhé.`);}catch(e){show(e.message);}finally{setBusy(false);}}
  async function download(){if(!placed.length)return show('Thêm ít nhất một patch trước nhé.');setBusy(true);try{const blob=await makePNG();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='patchie-mockup.png';a.click();show('Đã tải mockup xuống máy.');}catch(e){show('Không tạo được ảnh mockup.');}finally{setBusy(false);}}
  return <main className="shell"><header className="topbar"><a className="brand" href="/"><span className="brand-mark">P</span> Patchie<span className="brand-studio">STUDIO</span></a><div className="toplinks"><span>Áo base · Patch thêu ủi</span><a href="/admin">Quản trị ↗</a></div></header>
    <section className="hero"><div><div className="eyebrow">YOUR TEE, YOUR LITTLE WORLD</div><h1>Tự tạo chiếc áo<br/><em>của riêng bạn.</em></h1><p>Chọn patch, kéo thả thử trên áo rồi lưu mẫu. Tự ủi tại nhà hoặc gửi shop hoàn thiện giúp bạn.</p></div><div className="hero-sticker">made<br/>by you <span>✳</span></div></section>
    <div className="workspace"><aside className="panel picker"><div className="panel-title"><div><small>01 / CHỌN PATCH</small><h2>Patch của bạn</h2></div><span className="counter">{placed.length}/6</span></div><p className="muted">Mỗi patch thêu ủi nhỏ khoảng 1 cm.</p><div className="patch-grid">{catalog.patches.map(p=><button key={p.id} className={`patch-card ${chosen===p.id?'picked':''}`} onClick={()=>setChosen(p.id)}><span className="patch-img"><img src={p.image_url} alt={p.name}/></span><b>{p.name}</b><small>~ 1 cm</small></button>)}</div><button className="button dark full" onClick={add}>＋ Thêm patch lên áo</button><div className="tip"><span>✦</span><p>Kéo patch trên áo để thử vị trí. Vì patch thật chỉ 1 cm, preview hiển thị nhỏ tương ứng.</p></div><hr/><div className="form-field"><label>Mẫu áo</label><select value={productId} onChange={e=>setProductId(e.target.value)}>{catalog.products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.color}</option>)}</select></div><div className="form-field"><label>Size</label><div className="size-row">{sizes.map(s=><button key={s} className={`size ${size===s?'on':''}`} onClick={()=>setSize(s)}>{s}</button>)}</div></div></aside>
      <section className="preview-col"><div className="preview-head"><div><small>02 / SẮP XẾP</small><h2>Thử phối trên áo</h2></div><div className="editor-actions"><button onClick={()=>setPlaced([])}>Xóa hết</button><button onClick={download} disabled={busy}>Tải mockup ↓</button></div></div><div className="preview-card"><div className="stage" ref={stage} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerLeave={()=>drag.current=null}><img className="tee" src={product?.image_url||'/assets/blank-tee.webp'} alt="Áo thun base"/>{placed.map((x,i)=>{const p=catalog.patches.find(y=>y.id===x.patchId);return <button key={x.uid} className="placed-patch" aria-label={`Kéo patch ${p?.name}`} style={{left:`${x.x*100}%`,top:`${x.y*100}%`,zIndex:i+1}} onPointerDown={e=>{e.preventDefault();drag.current=x.uid;e.currentTarget.setPointerCapture(e.pointerId)}}><img src={p?.image_url} alt={p?.name}/></button>})}{!placed.length&&<div className="empty-nudge">Chọn patch rồi nhấn “Thêm patch lên áo” <span>↗</span></div>}</div><div className="preview-foot"><span>✳ Patch thật khoảng 1 cm</span><span>Kéo patch để đổi vị trí</span></div></div><div className="method-row"><button className={mode==='diy'?'method active':'method'} onClick={()=>setMode('diy')}><span>🏠</span><b>Tự ủi tại nhà</b><small>Nhận patch rời cùng áo base</small></button><button className={mode==='shop'?'method active':'method'} onClick={()=>setMode('shop')}><span>🪡</span><b>Shop ủi giúp</b><small>Gửi mockup, shop làm theo</small></button></div></section>
      <aside className="panel request"><div className="panel-title"><div><small>03 / ĐẶT ĐƠN</small><h2>Lưu thiết kế</h2></div><span className="spark">✳</span></div><p className="muted">Không thanh toán trên website. Shop xác nhận giá và giao hàng qua Messenger.</p><div className="form-field"><label>Tên của bạn</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Tên để shop nhận diện" maxLength={80}/></div><div className="form-field"><label>Ghi chú <span>(không bắt buộc)</span></label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Màu áo, vị trí patch mong muốn…" rows={3} maxLength={1200}/></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{catalog.settings.privacyText}</span></label><button className="button coral full send-button" onClick={send} disabled={busy}>{busy?'Đang tạo đơn…':'Đặt đơn'}</button>{order&&<div className="order-code-card"><small>Mã đơn của bạn</small><div className="order-code-row"><code>{order.id}</code><button type="button" onClick={copyOrder}>Copy</button><button type="button" className="messenger-btn" onClick={openMessenger} aria-label="Mở Messenger"><span>m</span></button></div><p>Copy mã này và gửi qua Messenger để shop mở đúng mockup trong admin.</p></div>}<div className="privacy-note">Mockup được lưu để shop xem theo mã đơn và sẽ tự xóa sau thời hạn cài đặt.</div><div className="tiny-note">Giá, mẫu áo và tồn kho sẽ được shop xác nhận trước khi chốt.</div></aside></div>
    <footer><span>Patchie · Customize your everyday</span><span>Chọn patch · Tạo mockup · Gửi shop</span></footer>{toast&&<div className="toast">{toast}</div>}</main>;
}
