-- Run once in Supabase SQL Editor for the fast order flow.
-- Orders can be created before their mockup upload finishes.
alter table public.designs alter column image_path drop not null;

-- Create Patch Market order tables when the main schema was installed before
-- Patch Market was added.
create table if not exists public.patch_orders (
  id text primary key default ('PM-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  customer_name text not null,
  customer_phone text not null default '',
  shipping_address text not null default '',
  total_price integer not null default 0,
  note text not null default '',
  status text not null default 'new' check (status in ('new','confirmed','completed','closed')),
  created_at timestamptz not null default now()
);
create table if not exists public.patch_order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.patch_orders(id) on delete cascade,
  patch_id text not null references public.patches(id) on delete restrict,
  patch_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null default 0,
  line_total integer not null default 0
);
create index if not exists patch_orders_created_at_idx on public.patch_orders(created_at desc);
alter table public.patch_orders enable row level security;
alter table public.patch_order_items enable row level security;
grant all on table public.patch_orders to service_role;
grant all on table public.patch_order_items to service_role;
grant usage, select on sequence public.patch_order_items_id_seq to service_role;
notify pgrst, 'reload schema';

-- Product groups use stable ids stored in product_type; the display label is
-- editable in settings, so custom groups must not be restricted to shirt/bag.
alter table public.products drop constraint if exists products_product_type_check;
alter table public.products add column if not exists size_guide text not null default '';

alter table public.designs drop constraint if exists designs_status_check;
alter table public.designs
  add constraint designs_status_check
  check (status in ('processing','new','review','confirmed','completed','closed'));

update storage.buckets
set allowed_mime_types = array['image/png','image/webp']
where id = 'design-mockups';
