'use client';

import { useEffect, useState } from 'react';
import { createBrowserClient } from '@supabase/ssr';

const money=value=>`${new Intl.NumberFormat('vi-VN').format(Number(value)||0)}đ`;

export default function PatchMarketOrders(){
  const [user,setUser]=useState(null),[email,setEmail]=useState(''),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
  const supa=()=>createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
  const call=async(path,options={})=>{const response=await fetch(`/api/admin/${path}`,options),data=await response.json();if(!response.ok)throw Error(data.error||'Có lỗi xảy ra.');return data;};
  const refresh=async()=>{setLoading(true);try{const {data:{user:current}}=await supa().auth.getUser();setUser(current);if(current){const data=await call('patch-orders');setOrders(data.items||[]);}}catch(error){setMessage(error.message);}finally{setLoading(false);}};
  useEffect(()=>{refresh();},[]);
  async function login(event){event.preventDefault();setMessage('Đang gửi link đăng nhập…');const {error}=await supa().auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}/auth/callback`}});setMessage(error?.message||'Đã gửi link đăng nhập vào email.');}
  async function updateStatus(id,status){try{await call('patch-orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});setOrders(current=>current.map(order=>order.id===id?{...order,status}:order));}catch(error){setMessage(error.message);}}
  if(loading)return <main className="admin-shell"><div className="admin-loading">Đang tải đơn Patch Market…</div></main>;
  if(!user)return <main className="admin-shell"><div className="login-card"><a className="brand" href="/"><span className="brand-mark">P</span> Patchie</a><div className="eyebrow">PATCH MARKET ADMIN</div><h1>Đăng nhập shop</h1><p>Đăng nhập bằng email quản trị đã cài trên Vercel.</p><form onSubmit={login}><label>Email quản trị<input type="email" required value={email} onChange={event=>setEmail(event.target.value)} placeholder="ban@patchie.vn"/></label><button className="button dark full">Gửi link đăng nhập</button></form>{message&&<p className="admin-msg">{message}</p>}<a className="back-link" href="/admin/market">← Về Patch Market</a></div></main>;
  return <main className="admin-shell"><header className="admin-top"><a className="brand" href="/admin/market"><span className="brand-mark">P</span> Patchie <small>PATCH MARKET</small></a><div>{user.email}<button className="admin-logout" onClick={async()=>{await supa().auth.signOut();setUser(null);}}>Đăng xuất</button></div></header><div className="admin-layout"><nav className="admin-nav"><a href="/admin">← Dashboard</a><a href="/admin/market">Patch Market</a><a className="sel" href="/admin/market/orders">Đơn patch</a><a href="/patches" target="_blank">Mở trang ↗</a></nav><section className="admin-content"><div className="admin-heading"><div><small>PATCH MARKET</small><h1>Đơn mua patch riêng</h1></div><a href="/patches" target="_blank">Xem trang ↗</a></div>{message&&<div className="admin-msg">{message}</div>}<div className="admin-card"><p className="admin-help">Khách tạo mã đơn trên Patch Market rồi gửi nội dung qua Messenger. Shop cập nhật trạng thái ở đây để theo dõi.</p><div className="table-scroll"><table><thead><tr><th>Mã / thời gian</th><th>Khách nhận hàng</th><th>Patch</th><th>Tổng</th><th>Trạng thái</th></tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><b>{order.id}</b><small>{new Date(order.created_at).toLocaleString('vi-VN')}</small></td><td>{order.customer_name}<small>{order.customer_phone}<br/>{order.shipping_address}</small></td><td>{(order.patch_order_items||[]).map(item=><div key={item.id}>{item.patch_name} × {item.quantity}</div>)}</td><td><b>{money(order.total_price)}</b></td><td><select value={order.status} onChange={event=>updateStatus(order.id,event.target.value)}>{['new','confirmed','completed','closed'].map(status=><option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table>{!orders.length&&<p>Chưa có đơn patch riêng.</p>}</div></div></section></div></main>;
}
